name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: pcov

      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

      - name: Execute Static Analysis via PHPStan
        run: vendor/bin/phpstan analyse

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit -d memory_limit=512M --coverage-clover clover.xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./clover.xml
