name: Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP CodeStyle Fixer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  tests:
    needs: php-cs-fixer
    runs-on: ubuntu-latest
    steps:
      - name: Set Up PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: pcov

      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit -d memory_limit=512M --coverage-clover clover.xml

      - name: Execute Static Analysis via PHPStan
        run: vendor/bin/phpstan analyse

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./clover.xml
